webtalk_init -webtalk_dir C:/Code/Vivado/master_slave_D_filp_flop/master_slave_D_filp_flop/master_slave_D_filp_flop.sim/sim_1/behav/xsim.dir/time_simulation_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon May 23 11:14:13 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1909853" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "e10e2e70-3e35-4042-adb6-997ad4f6e4c1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "df68c833fd0545fa9d5e94b6f921b1bd" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "22" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2592 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "430 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.00_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7196_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1201548905 -regid "" -xml C:/Code/Vivado/master_slave_D_filp_flop/master_slave_D_filp_flop/master_slave_D_filp_flop.sim/sim_1/behav/xsim.dir/time_simulation_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Code/Vivado/master_slave_D_filp_flop/master_slave_D_filp_flop/master_slave_D_filp_flop.sim/sim_1/behav/xsim.dir/time_simulation_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Code/Vivado/master_slave_D_filp_flop/master_slave_D_filp_flop/master_slave_D_filp_flop.sim/sim_1/behav/xsim.dir/time_simulation_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
